name: Keploy Cloud API Test Suite

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  keploy-cloud:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: todos
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Install Keploy CLI
        run: go install github.com/keploy/keploy@latest

      - name: Set environment variables
        run: |
          echo "DATABASE_URL=postgresql://goTodo_owner:npg_trHazBIVv4W8@ep-lingering-snowflake-a11jwena-pooler.ap-southeast-1.aws.neon.tech/goTodo?sslmode=require" >> $GITHUB_ENV
          echo "PORT=8080" >> $GITHUB_ENV
          echo "KEPLOY_API_KEY=${{ secrets.KEPLOY_API_KEY }}" >> $GITHUB_ENV

      - name: Run your app in background
        run: |
          nohup go run main.go & sleep 5

      - name: Run Keploy Cloud Test Suite
        run: |
          keploy test-suite \
            --app=59f21eae-5604-4221-bbe8-2184afd21752 \
            --base-path http://localhost:8080 \
            --cloud
